#!/usr/bin/env node
// One-off back-fill: create a `shows` row for every existing host on
// every slate, and link each host's slots to their new show.
//
// Approach: read hosts via `wrangler d1 execute --json`, slugify names
// in Node (handles collisions deterministically with -2/-3 suffixes),
// emit a single SQL file with INSERTs + UPDATEs, then apply it via
// `wrangler d1 execute --file`.
//
// Idempotent: skips a host who already has a show on the slate (joined
// by host_id + slate_id).
//
// Run after migration 0008:
//   node scripts/backfill_shows.mjs --remote
//   node scripts/backfill_shows.mjs --local    # for local D1

import { execSync } from 'node:child_process';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const remote = process.argv.includes('--remote');
const flag = remote ? '--remote' : '--local';

function wranglerQuery(sql) {
  // wrangler's --command is finicky with multi-line input; collapse
  // whitespace so it stays a single argv element regardless of how
  // we wrote it in JS.
  const oneLine = sql.replace(/\s+/g, ' ').trim();
  const out = execSync(
    `npx wrangler d1 execute slate-podcast ${flag} --json --command ${JSON.stringify(oneLine)}`,
    { stdio: ['ignore', 'pipe', 'inherit'], maxBuffer: 16 * 1024 * 1024 },
  ).toString();
  const parsed = JSON.parse(out);
  return parsed[0]?.results ?? [];
}

function wranglerFile(path) {
  execSync(
    `npx wrangler d1 execute slate-podcast ${flag} --file=${path}`,
    { stdio: 'inherit' },
  );
}

function slugify(s) {
  return String(s)
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64) || 'show';
}

function randomId() {
  return [...crypto.getRandomValues(new Uint8Array(10))]
    .map(b => b.toString(16).padStart(2, '0')).join('');
}

function sqlString(s) {
  if (s === null || s === undefined) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

console.error('Querying hosts that need a show row…');
const hosts = wranglerQuery(`
  SELECT sm.slate_id, sm.user_id, sm.show_name, sm.show_logo_url, sm.profile_body,
         u.email, u.display_name
  FROM slate_members sm
  JOIN users u ON u.id = sm.user_id
  WHERE sm.role = 'host'
    AND NOT EXISTS (
      SELECT 1 FROM shows s
      WHERE s.slate_id = sm.slate_id AND s.host_id = sm.user_id
    )
`);

if (hosts.length === 0) {
  console.error('No hosts to back-fill. Done.');
  process.exit(0);
}

console.error(`Found ${hosts.length} host(s) needing a default show.`);

// Per-slate slug collision tracker. Pre-seed with existing show slugs.
const existing = wranglerQuery(`SELECT slate_id, slug FROM shows`);
const usedSlugs = new Map(); // slate_id -> Set<slug>
for (const r of existing) {
  if (!usedSlugs.has(r.slate_id)) usedSlugs.set(r.slate_id, new Set());
  usedSlugs.get(r.slate_id).add(r.slug);
}

const inserts = [];
const slotUpdates = [];

for (const h of hosts) {
  const emailLocal = String(h.email).split('@')[0];
  // Prefer the host's show_name (their already-set show identity), then
  // their personal display_name, then the email-local part as final
  // fallback. The user OK'd "username show" as the default — that's
  // emailLocal when nothing else is set.
  const rawName = h.show_name?.trim() || h.display_name?.trim() || emailLocal;
  let slug = slugify(rawName);

  if (!usedSlugs.has(h.slate_id)) usedSlugs.set(h.slate_id, new Set());
  const slateSlugs = usedSlugs.get(h.slate_id);
  if (slateSlugs.has(slug)) {
    let i = 2;
    while (slateSlugs.has(`${slug}-${i}`)) i++;
    slug = `${slug}-${i}`;
  }
  slateSlugs.add(slug);

  const showId = `show_${randomId()}`;
  inserts.push(
    `INSERT INTO shows (id, slate_id, host_id, slug, name, cover_image_url, wiki_body, created_at) VALUES (` +
    [
      sqlString(showId),
      sqlString(h.slate_id),
      sqlString(h.user_id),
      sqlString(slug),
      sqlString(rawName),
      sqlString(h.show_logo_url ?? null),
      sqlString(h.profile_body ?? null),
      'unixepoch()',
    ].join(', ') + ');'
  );

  // Link this host's existing slots on the slate to the new show. Only
  // touches rows where show_id is null — defensive in case anything was
  // pre-linked.
  slotUpdates.push(
    `UPDATE slots SET show_id = ${sqlString(showId)} ` +
    `WHERE slate_id = ${sqlString(h.slate_id)} ` +
    `AND host_id = ${sqlString(h.user_id)} AND show_id IS NULL;`
  );

  console.error(`  ${h.email} → show "${rawName}" (slug=${slug})`);
}

const sqlBody = [
  '-- Auto-generated by scripts/backfill_shows.mjs',
  '-- Creates one show per existing role=host slate_member + links their slots.',
  '',
  ...inserts,
  '',
  ...slotUpdates,
  '',
].join('\n');

const tmp = mkdtempSync(join(tmpdir(), 'backfill_shows_'));
const sqlPath = join(tmp, 'backfill.sql');
writeFileSync(sqlPath, sqlBody);

console.error(`\nApplying ${inserts.length} INSERTs + ${slotUpdates.length} UPDATEs to ${remote ? 'REMOTE' : 'LOCAL'} D1…`);
wranglerFile(sqlPath);
console.error('Done.');
